server:
  port: 8097

# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: springcloud-gateway-witheureka
  redis:
    host: localhost
    port: 6379
    database: 0
  profiles:
    active: method_route
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: service-hi
        uri: lb://springcloud-eureka-serviceprovider # lb 标识负载均衡loadbalance，SERVICE-HI是服务名称
        predicates:
        - Path=/demo/** # 所有demo开头的请求走这个路由
        filters:
        - StripPrefix=1 # 转发之前将/demo去掉

# 添加 eureka 注册中心集群
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka2:8001/eureka/,http://admin:123456@eureka3:8002/eureka/,http://admin:123456@eureka2:8003/eureka/